build.sbt
project/bintray.sbt
project/plugins.sbt
sbt-jmh-tester/project/plugins.sbt
sbt-jmh-tester/src/main/scala/test/Test.scala
src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala
src/main/scala/pl/project13/scala/sbt/package.scala

Changes made for auto-plugin. I also added the sbt-jhm-tester subdirectory: just cd into it, open sbt and test sbt-jhm, e.g. by executing `run`.
Additionally I (hopefully) improved/simplified some things.

Convert to auto-plugin (closes #14)

---

src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala
src/sbt-test/sbt-jmh/custom-runner/build.sbt
src/sbt-test/sbt-jmh/jmh-asm/build.sbt
src/sbt-test/sbt-jmh/run/build.sbt
src/sbt-test/sbt-jmh/runMain/build.sbt

When JmhPlugin is on all project by default, it inserts an undesirable `jmh:compile` dependency on each project's `run`.
E.g. 
```
sbt (spandex)> inspect spandex-http/run
[info] Input task: Unit
[info] Description:
[info] 	Runs a main class, passing along arguments provided on the command line.
[info] Provided by:
[info] 	{file:/usr/local/src/socrata/spandex/}spandex-http/compile:run
[info] Defined at:
[info] 	(sbt.Defaults) Defaults.scala:762
[info] 	(pl.project13.scala.sbt.JmhPlugin) JmhPlugin.scala:83
[info] Dependencies:
[info] 	spandex-http/compile:run::runner
[info] 	spandex-http/compile:run::streams
[info] 	spandex-http/jmh:compile
[info] 	spandex-http/runtime:fullClasspath
[info] 	spandex-http/compile:run::mainClass
...
```
Disabling is one call `.disablePlugins(JmhPlugin)` on …

JmhPlugin off except when enabled

---

build.sbt
src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala
src/sbt-test/sbt-jmh/custom-runner/build.sbt
src/sbt-test/sbt-jmh/custom-runner/test
src/sbt-test/sbt-jmh/jmh-asm/test
src/sbt-test/sbt-jmh/run/test
src/sbt-test/sbt-jmh/runMain/test
version.sbt

* Made the JMH scope inherit Test to automatically get the benhcmark code on the path to avoid the special compile step and not write to the same class files directory
* Cached the generation of sources and resources
* Use sourceGenerators and resourceGenerators
* All interactions with JMH are now scoped to jmh:*

Make the JMH plugin only regenerate and recompile on source changes.

---

src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala

As mentioned in https://github.com/ktoso/sbt-jmh/issues/63#issuecomment-230509786 one can hack around the hardcoded config that is used for `classDirectory` and `dependencyClasspath` (both are taken from the `Compile` config).
This change allows the user to set
```
classDirectory in Jmh := (classDirectory in Test).value
dependencyClasspath in Jmh := (dependencyClasspath in Test).value
```
so that jmh will use the appropriate values.
Not sure if this change provides enough value to be merged, at least it seems to be cleaner when having benchmark code in the Test config.

Make classDirectory+dependencyClasspath configurable

---

README.md
notes/0.2.16.markdown
plugin/src/main/resources/sbt-jmh.properties
version.sbt

Sorry for pushing you but it'd be glad if you could publish sbt-jmh to maven repo (if you have time!) :) 
If I'm correct the upcoming sbt-jmh plugin version is 0.2.16? 
P.S.
If you think it'd be better for us to wait for JMH 1.15 release. Let's wait! :D Please close this PR if so :)
ref. http://mail.openjdk.java.net/pipermail/jmh-dev/2016-September/002351.html

Upgrade to JMH version 1.14.1

---

extras/src/main/java/pl/project13/scala/jmh/extras/profiler/FlightRecordingProfiler.java

Fix setting FlightRecorderOptions by appending them just once. Before this
fix, they were added multiple times due to mutation of
`startFlighRecordingOptions`. Mutable code is hard!
Fixes #85

Fix for #85

---

.travis.yml
README.md
build.sbt
plugin/src/main/resources/sbt-jmh.properties
plugin/src/sbt-test/sbt-jmh/custom-runner/src/main/scala/com/example/CustomRunnerApp.scala
plugin/src/sbt-test/sbt-jmh/runMain/src/main/scala/com/example/CustomRunnerApp.scala
project/build.properties
version.sbt

This PR fixes #115. 
I had to update the two `CustomRunnerApp` in the scripted tests two use the `main()` method. I ran into the `IncompatibleClassChangeError` issue, changes fix #66.
Now you have to use `^ scripted` and `^ publishSigned` to cross-compile with the correct sbt version (see the [0.13.16-M1](https://github.com/sbt/sbt/releases/tag/v0.13.16-M1) release notes).

Cross-compile the plugin against 0.13.15 and 1.0.0-M6

---

build.sbt
plugin/src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala
plugin/src/main/scala/pl/project13/scala/sbt/package.scala
project/plugins.sbt

I only added license header in `plugin` project without `extras` project because `extras` didn't specific license in `build.sbt`. I think we could move sbt-key - `licenses` to `commonSettings` to let all projects with Apache-2.0. Since JMH is used GPLv2 with Classpath exception as OpenJDK, I think it should be fine.

Add license header.

---

extras/src/main/java/jmh/extras/Async.java
extras/src/main/java/jmh/extras/JFR.java
extras/src/main/java/pl/project13/scala/jmh/extras/profiler/AsyncProfiler.java
extras/src/main/java/pl/project13/scala/jmh/extras/profiler/Directions.java
extras/src/main/java/pl/project13/scala/jmh/extras/profiler/FlightRecordingProfiler.java
extras/src/main/java/pl/project13/scala/jmh/extras/profiler/JfrEventType.java
extras/src/main/java/pl/project13/scala/jmh/extras/profiler/NoResult.java
extras/src/main/java/pl/project13/scala/jmh/extras/profiler/ProfilerUtils.java
plugin/src/sbt-test/sbt-jmh/with-FlightRecorderProfiler/test

Existing Flight Recorder profiler modified to:
- Discard samples collected during the warmup period
- By default, use AsyncGetCallTrace based sampling
- Make `stackdepth` configurable and increase the default
- Optionally, generate flamegraphs for (requires local clone of
[brendangregg/FlameGraph](https://github.com/brendangregg/FlameGraph) and a local clone and build of
[chrishantha/jfr-flame-graph](https://github.com/chrishantha/jfr-flame-graph).)
Support async-profiler:
- Requires local clone and build of [jvm-profiling-tools/async-profiler](https://github.com/jvm-profiling-tools/async-profiler)
- Samples only collected after warmup has completed
- CPU and HEAP events supported.
- Optionally, generate flame graphs
async-profiler is primarily Linux based, but it also has preliminary …

Support async-profiler, improve JFR profiler

---

README.md

Newer version of sbt expect `evaluated` instead of `value` on `InputKey`
http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html#Migrating+with

Update benchmark in `src/test` example

---

extras/src/main/java/pl/project13/scala/jmh/extras/profiler/AsyncProfiler.java
extras/src/main/java/pl/project13/scala/jmh/extras/profiler/FlightRecordingProfiler.java

- Support Flight Recorder on OpenJDK 11
- Enable -XX:+DebugNonSafePoints for async-profiler, by default.
- Add an option to async-profiler to also dump its data in JFR format.
Fixes #156

Improvements to profilers

---

.travis.yml

Enable caching of SBT and downloaded artifacts
Use openjdk8 rather than oraclejdk.

Adopt best practices in Travis Build

---

.travis.yml

Use dist:trusty for pre-installed OracleJDK 8

---

extras/src/main/java/pl/project13/scala/jmh/extras/profiler/FlightRecordingProfiler.java
plugin/src/sbt-test/sbt-jmh/with-FlightRecorderProfiler/test

Better version of #171.
The readme seems to indicate that JFR files contain their names, but they seem hard coded to "profile.jfr" (https://github.com/ktoso/sbt-jmh/blob/master/extras/src/main/java/pl/project13/scala/jmh/extras/profiler/FlightRecordingProfiler.java#L36).
This change prefixes the name with the current benchmark params, so each benchmark method gets its own profile jfr output.
I see that it used to support params as well in https://github.com/ktoso/sbt-jmh/blame/d70cd26695e14392fed65032cab42359c48c103d/extras/src/main/java/pl/project13/scala/jmh/extras/profiler/FlightRecordingProfiler.java#L100.
Now including update to test.

Add benchmark method name to output JFR filename 

---

extras/src/main/java/pl/project13/scala/jmh/extras/profiler/FlightRecordingProfiler.java

`replaceAll` causes on most environments weird behaviour, cause it fails to find jcmd

minor fix to jcmd lookup

---

README.md
build.sbt
project/bintray.sbt
project/build.properties
project/plugins.sbt
sbt-jmh-tester/project/plugins.sbt

As part of the 0.4.0 release, lets mandate SBT 1.3.x.

Drop SBT 0.13.x support and update SBT plugins

---

plugin/src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala

Importing a Jmh build target in IntelliJ or Metals triggers the Jmh source generation which triggers the compilation.
This is not user friendly because:
- it takes time to import the project
- it can compile in error and then it makes the entire import fail (we need more granularity in BSP to handle individual failures)
Importing the Jmh build target is often not useful because it shares its sources with the `Compile` or `Test` build target.
Related discussions:
- https://github.com/scalameta/metals/pull/2895
- https://github.com/sbt/sbt/issues/6546
- https://github.com/lampepfl/dotty/pull/11687
- https://github.com/scala/scala/pull/9673

Disable BSP in the Jmh config

---

README.md

In particular `jmh:run` because `Jmh/run` (I also replaced unprefixed use of run/runMain) and `foo in bar` becomes `bar / foo`. Additionally, I simplified the example involving customized settings to not rely on a separate `bench/build.sbt` file since that's an unusual way to do things.

README.md: Use modern syntax

---

sbt-jmh-tester/project/plugins.sbt

It fails on attempt to use like:
```
/Users/catap/src/sbt-jmh/sbt-jmh-tester/project/plugins.sbt:2: error: object Source is not a member of package sbt.io
val is = io.Source.fromFile(new File("../version.sbt")).mkString
^
```

Fix `sbt-jmh-tester`

---

.github/dependabot.yml
.github/release-drafter.yml
.github/workflows/ci.yml
.github/workflows/release-drafter.yml
.github/workflows/scala-steward.yml
build.sbt
plugin/src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala
project/build.properties
project/plugins.sbt
version.sbt

Update sbt to 1.9.0, migrate to new sbt syntax && Modernize a bit the CI (add ScalaSteward, dependabot and release-drafter)

---

plugin/src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala

Forking has a couple of benefits:
1. It runs with the full modules for the JVM, so that it doesn't error if you use something from a module such as java.sql
2. If the generation throws an exception, it doesn't kill sbt outright.
Taken from https://github.com/pawel-wiejacha/sbt-jmh/commit/a916d771b2d75dce3404cce5cba282884f2251c6
Fixes: #190
Co-authored-by: pawel-wiejacha

fix: Use ForkRun for generateJmhSourcesAndResources

---

plugin/src/sbt-test/sbt-jmh/custom-runner/build.sbt
plugin/src/sbt-test/sbt-jmh/custom-runner/test
plugin/src/sbt-test/sbt-jmh/generator-error/test
plugin/src/sbt-test/sbt-jmh/jmh-asm/test
plugin/src/sbt-test/sbt-jmh/run/test
plugin/src/sbt-test/sbt-jmh/runMain/test

prepare sbt 2.x
- https://github.com/sbt/sbt/pull/7703

use new slash syntax

---

plugin/src/sbt-test/sbt-jmh/custom-runner/src/main/scala/com/example/CustomRunnerApp.scala
plugin/src/sbt-test/sbt-jmh/runMain/src/main/scala/com/example/CustomRunnerApp.scala

- use `JavaConverters` instead of `JavaConversions`
- replace old deprecated unicode arrow `⇒`
- add parentheses

prepare sbt 2.x in test code
